Set non-default SSH port

diff --git a/xiringuito b/xiringuito
--- a/xiringuito
+++ b/xiringuito
@@ -11,6 +11,7 @@ function print_help() {
   echo "Usage: ${0} [OPTIONS] [SSH_USER@]SSH_SERVER [NETWORK1, NETWORK2, ... NETWORKx]"
   echo
   echo "OPTIONS"
+  echo "-p SSH_PORT            use non-default SSH port"
   echo "-k PRIVATE_KEY_PATH    use specific SSH private key"
   echo "-f MAX_FAILED_PINGS    fail connection after X ping failures"
   echo
@@ -40,8 +41,20 @@ if [[ ${#} -lt 1 ]]; then
   exit 1
 fi
 
-while getopts "k:f:DXch" o; do
+while getopts "p:k:f:DXch" o; do
   case ${o} in
+    p)
+      SSH_PORT=${OPTARG}
+      if [[ ! ${SSH_PORT} =~ ^[0-9]+$ ]]; then
+        echo "SSH port should be a number, while this is not: ${SSH_PORT}"
+        exit 1
+      fi
+      if [[ ${SSH_PORT} -lt 1 || ${SSH_PORT} -gt 65535 ]]; then
+        echo "Invalid port number: ${SSH_PORT} (should be between 1 and 65535)"
+        exit 1
+      fi
+      SSH_PORT_OPTS="-oPort=${SSH_PORT}"
+      ;;
     k)
       PRIVATE_KEY_PATH=${OPTARG}
       if [[ ! -f "${PRIVATE_KEY_PATH}" ]]; then
@@ -119,7 +132,7 @@ fi
 declare -r TUNNEL_ID=$(cat ${TUNNEL_ID_FILE})
 declare -r REMOTE_PATH="/tmp/xiringuito.${TUNNEL_ID}"
 
-declare -r SSH_OPTS="-oLogLevel=${SSH_LOG_LEVEL:-ERROR} -oConnectionAttempts=3 -oConnectTimeout=5 ${SSH_PRIVATE_KEY_OPTS} ${SSH_EXTRA_OPTS}"
+declare -r SSH_OPTS="-oLogLevel=${SSH_LOG_LEVEL:-ERROR} -oConnectionAttempts=3 -oConnectTimeout=5 ${SSH_PRIVATE_KEY_OPTS} ${SSH_PORT_OPTS} ${SSH_EXTRA_OPTS}"
 
 if [[ ${KERNEL} == linux ]]; then
   declare -r LOCAL_TUNNEL_ID=${TUNNEL_ID}
